import type { Collection, Product, SocialPost } from "@/types/store";

const images = {
  charcoalTee:
    "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=85",
  whiteTee:
    "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1200&q=85",
  graphicTee:
    "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=1200&q=85",
  modelDark:
    "https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=1600&q=85",
  modelWhite:
    "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1600&q=85",
  street:
    "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1600&q=85",
  fabric:
    "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1600&q=85",
  editorial:
    "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=1600&q=85",
  heavyweightBlack:
    "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=1200&q=85",
  vintageWash:
    "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=1200&q=85",
  essentialHeather:
    "https://images.unsplash.com/photo-1527719327859-c6ce80353573?auto=format&fit=crop&w=1200&q=85",
  oversizedSage:
    "https://images.unsplash.com/photo-1574180566232-aaad1b5b8450?auto=format&fit=crop&w=1200&q=85",
  cropWhite:
    "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=1200&q=85",
  skaterDark:
    "https://images.unsplash.com/photo-1563630423918-b58f07336ac9?auto=format&fit=crop&w=1200&q=85",
};

export const heroImage =
  "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=2200&q=90";

const allProducts: Product[] = [
  {
    id: "shadow-01",
    slug: "shadow-weight-tee",
    name: "Shadow Weight Tee",
    description: "A relaxed heavyweight tee in garment-dyed charcoal cotton. Double-stitched seams and a high ribbed collar.",
    price: 2490,
    compareAtPrice: 2890,
    category: "240 GSM / Charcoal",
    collection: "The Uniform",
    images: [images.charcoalTee, images.modelDark],
    colors: [{ name: "Charcoal", hex: "#282725" }],
    sizes: ["S", "M", "L", "XL"],
    badge: "New",
    stockStatus: "in_stock",
    featured: true,
    bestSeller: true,
    newArrival: true,
    rating: 4.8,
    reviewCount: 42,
  },
  {
    id: "signal-02",
    slug: "signal-study-tee",
    name: "Signal Study Tee",
    description: "A clean bone tee with a restrained chest graphic. Lightweight 180gsm cotton perfect for layering.",
    price: 2690,
    compareAtPrice: 2990,
    category: "180 GSM / Bone",
    collection: "Graphic Studies",
    images: [images.whiteTee, images.modelWhite],
    colors: [{ name: "Bone", hex: "#e9e4da" }],
    sizes: ["S", "M", "L", "XL"],
    badge: "New",
    stockStatus: "in_stock",
    featured: true,
    bestSeller: false,
    newArrival: true,
    rating: 4.6,
    reviewCount: 18,
  },
  {
    id: "archive-03",
    slug: "archive-no-03",
    name: "Archive No. 03",
    description: "A washed ink graphic tee with an oversized shape. Screen printed with environmentally friendly inks.",
    price: 2890,
    category: "240 GSM / Washed ink",
    collection: "Graphic Studies",
    images: [images.graphicTee, images.street],
    colors: [{ name: "Washed ink", hex: "#464540" }],
    sizes: ["S", "M", "L", "XL", "XXL"],
    badge: "Limited",
    stockStatus: "low_stock",
    featured: true,
    bestSeller: false,
    newArrival: true,
    rating: 5.0,
    reviewCount: 12,
  },
  {
    id: "static-04",
    slug: "static-oversized-tee",
    name: "Static Oversized Tee",
    description: "A generous, dropped-shoulder tee in deep coal jersey. Designed to drape rather than cling.",
    price: 2490,
    category: "240 GSM / Coal",
    collection: "The Uniform",
    images: [images.modelDark, images.charcoalTee],
    colors: [{ name: "Coal", hex: "#151515" }],
    sizes: ["XS", "S", "M", "L", "XL"],
    stockStatus: "in_stock",
    featured: false,
    bestSeller: false,
    newArrival: true,
    rating: 4.5,
    reviewCount: 28,
  },
  {
    id: "mono-05",
    slug: "monochrome-pocket-tee",
    name: "Monochrome Pocket Tee",
    description: "A refined pocket tee in soft ecru cotton. Subtle branding tab on the seam.",
    price: 2290,
    category: "220 GSM / Ecru",
    collection: "The Uniform",
    images: [images.essentialHeather, images.editorial],
    colors: [{ name: "Ecru", hex: "#ded9cf" }],
    sizes: ["S", "M", "L", "XL"],
    stockStatus: "in_stock",
    featured: false,
    bestSeller: true,
    newArrival: false,
    rating: 4.9,
    reviewCount: 84,
  },
  {
    id: "line-06",
    slug: "linework-heavy-tee",
    name: "Linework Heavy Tee",
    description: "A high-density black tee printed with an abstract line study.",
    price: 2690,
    category: "240 GSM / Ink",
    collection: "Graphic Studies",
    images: [images.skaterDark, images.street],
    colors: [{ name: "Ink", hex: "#20201e" }],
    sizes: ["S", "M", "L", "XL", "XXL"],
    badge: "Best seller",
    stockStatus: "in_stock",
    featured: true,
    bestSeller: true,
    newArrival: false,
    rating: 4.8,
    reviewCount: 51,
  },
  {
    id: "still-07",
    slug: "still-life-tee",
    name: "Still Life Tee",
    description: "A faded ash tee with a relaxed, lived-in finish. Pre-washed to eliminate shrinkage.",
    price: 2490,
    compareAtPrice: 2690,
    category: "240 GSM / Ash",
    collection: "Washed World",
    images: [images.vintageWash, images.fabric],
    colors: [{ name: "Ash", hex: "#aaa69f" }],
    sizes: ["S", "M", "L", "XL"],
    stockStatus: "low_stock",
    featured: false,
    bestSeller: true,
    newArrival: false,
    rating: 4.9,
    reviewCount: 36,
  },
  {
    id: "core-08",
    slug: "core-box-tee",
    name: "Core Box Tee",
    description: "A wide, cropped silhouette in optic white.",
    price: 2090,
    category: "210 GSM / White",
    collection: "The Uniform",
    images: [images.cropWhite, images.whiteTee],
    colors: [{ name: "White", hex: "#f8f9fa" }],
    sizes: ["XS", "S", "M", "L"],
    stockStatus: "in_stock",
    featured: false,
    bestSeller: false,
    newArrival: false,
    rating: 4.4,
    reviewCount: 15,
  },
  {
    id: "sage-09",
    slug: "botanical-dye-tee",
    name: "Botanical Dye Tee",
    description: "Pigment dyed using natural botanical extracts, giving a unique washed sage colour.",
    price: 2990,
    category: "240 GSM / Sage",
    collection: "Washed World",
    images: [images.oversizedSage, images.modelDark],
    colors: [{ name: "Sage", hex: "#7a8a76" }],
    sizes: ["S", "M", "L", "XL"],
    stockStatus: "sold_out",
    featured: false,
    bestSeller: false,
    newArrival: true,
    rating: 4.7,
    reviewCount: 6,
  },
  {
    id: "night-10",
    slug: "midnight-heavyweight",
    name: "Midnight Heavyweight",
    description: "Our thickest jersey cotton in a deep navy that appears black under low light.",
    price: 3290,
    category: "280 GSM / Midnight",
    collection: "The Uniform",
    images: [images.heavyweightBlack, images.editorial],
    colors: [{ name: "Midnight", hex: "#161b22" }],
    sizes: ["S", "M", "L", "XL", "XXL"],
    badge: "Premium",
    stockStatus: "in_stock",
    featured: false,
    bestSeller: false,
    newArrival: false,
    rating: 4.9,
    reviewCount: 22,
  },
  {
    id: "raw-11",
    slug: "raw-edge-tee",
    name: "Raw Edge Tee",
    description: "Unfinished hemlines that gracefully roll with wear. Vintage wash treatment.",
    price: 2790,
    category: "220 GSM / Cement",
    collection: "Washed World",
    images: [images.fabric, images.vintageWash],
    colors: [{ name: "Cement", hex: "#b4b2ac" }],
    sizes: ["S", "M", "L", "XL"],
    stockStatus: "low_stock",
    featured: false,
    bestSeller: false,
    newArrival: false,
    rating: 4.3,
    reviewCount: 11,
  },
  {
    id: "form-12",
    slug: "form-study-longsleeve",
    name: "Form Study Longsleeve",
    description: "A heavyweight longsleeve tee with ribbed cuffs and subtle architectural graphics.",
    price: 3490,
    category: "240 GSM / Concrete",
    collection: "Graphic Studies",
    images: [images.street, images.skaterDark],
    colors: [{ name: "Concrete", hex: "#8b8b8b" }],
    sizes: ["S", "M", "L", "XL"],
    stockStatus: "in_stock",
    featured: false,
    bestSeller: false,
    newArrival: true,
    rating: 5.0,
    reviewCount: 8,
  }
];

export const latestProducts = allProducts.filter(p => p.newArrival);
export const bestSellers = allProducts.filter(p => p.bestSeller);
export const products = allProducts;

export const collections: Collection[] = [
  {
    name: "The uniform",
    description: "Weight, proportion and repeat wear.",
    image: images.modelDark,
    href: "/shop?collection=the-uniform",
    span: "wide",
  },
  {
    name: "Graphic studies",
    description: "Marks made to outlast a season.",
    image: images.graphicTee,
    href: "/shop?collection=graphic-studies",
  },
  {
    name: "Washed world",
    description: "Colour with a lived-in memory.",
    image: images.fabric,
    href: "/shop?collection=washed-world",
  },
];

export const socialPosts: SocialPost[] = [
  { alt: "Véloce street uniform", image: images.street, href: "https://instagram.com" },
  { alt: "Véloce studio texture", image: images.fabric, href: "https://instagram.com" },
  { alt: "Véloce graphic study", image: images.graphicTee, href: "https://instagram.com" },
  { alt: "Véloce campaign portrait", image: images.editorial, href: "https://instagram.com" },
  { alt: "Véloce white tee editorial", image: images.modelWhite, href: "https://instagram.com" },
];

export const storyImage = images.editorial;
export const promotionImage = images.street;

export function getProductBySlug(slug: string) {
  return products.find((product) => product.slug === slug);
}
